name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
        with:
          determinate: true
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "nixcafe/develop-templates"
          rolling: true
          visibility: "public"
          include-output-paths: true
          # include-submodules: true
          # See: https://github.com/DeterminateSystems/flakehub-push/pull/182
          